

; STRINGS ARE DEFINED HERE

STRBEG::

	.GSTR STR?6,"PRSO"
	.GSTR STR?10,"cup"
	.GSTR STR?12,"A carton labelled ""Nutrimat/Computer Interface"" is sitting here."
	.GSTR STR?50," has no desirable effect."
	.GSTR STR?55,"You have lost your mind."
	.GSTR STR?109,"i l"
	.GSTR STR?162,""
	.GSTR STR?412,"You have to block the tiny robot panel."
	.GSTR STR?414,"You have to put some object in front of the panel."
	.GSTR STR?558,"You have to show an example of your intelligence to the screening door."
	.GSTR STR?561,"To show your intelligence, there are two specific items that you must be holding at the same time."
	.GSTR STR?633,"You have to cover your head with something."
	.GSTR STR?642,"You have to give your correct name to the Beast, or (in a rare moment of Bugblatter Beast perceptivity) it will be able to tell that you're lying. In addition, you can't tell the Beast your name if the Beast thinks it can't see you."
	.GSTR STR?676,"You have a limited number of moves to get the interface, after the Beast falls asleep and before the Fronurbdian Beasthunters arrive."
	.GSTR STR?684,"Try typing WHERE IS THE KEY while on the speedboat."
	.GSTR STR?712,"You have to figure out a way to get rid of the guards or the rifles permanently."
	.GSTR STR?773,"Try to give the towel to Arthur."
	.GSTR STR?780,"You have to talk to Prosser."
	.GSTR STR?841,"You have an opportunity here to remove your own common sense."
	.GSTR STR?844,"Taking the particle also has the beneficial side effect of getting you out of the Maze."
	.GSTR STR?943,"You have nothing to water the plant with."
	.GSTR STR?4,"Preaction"
	.GSTR STR?129,"a b"
	.GSTR STR?161,"SPLAT!!!!!"
	.GSTR STR?175,"Try: CONSULT GUIDE ABOUT (something)."
	.GSTR STR?405,"Use the hook above the hole."
	.GSTR STR?444,"ENJOY THE POETRY while the Captain reads the first verse. He will continue on and read the second verse."
	.GSTR STR?496,"Use the interface."
	.GSTR STR?828,"...so you must be microscopic-sized yourself."
	.GSTR STR?938,"Now wait."
	.GSTR STR?1063,"ATOMIC VECTOR PLOTTER"
	.GSTR STR?1076,"IMPROBABILITY DRIVES"
	.GSTR STR?1079,"LARGE PLUG"
	.GSTR STR?1081,"MAGRATHEA"
	.GSTR STR?22,"Like fog rolling in off the ocean, a shroud of blackness billows toward you. Unlike fog rolling in off the ocean, the blackness hits you like a sixteen-tonne truck..."
	.GSTR STR?72,"21,914"
	.GSTR STR?100,"fim"
	.GSTR STR?421,"Put something on the satchel, then push the button again."
	.GSTR STR?519,"READ THE MESSAGE THROUGH THE MAGNIFYING GLASS."
	.GSTR STR?563,"To prove your intelligence to the door, you must be holding TEA and NO TEA at the same time."
	.GSTR STR?656,"First you have to tell the Beast your name and cover your head with the towel."
	.GSTR STR?671,"First you'll have to figure out how to ""neutralize"" the Beast."
	.GSTR STR?758,"Naturally, the fluff is still in the handbag when you eventually get back to the Heart of Gold. You need only go to the Bridge or wherever you left the handbag, open it, and take the jacket fluff."
	.GSTR STR?66,"On the doormat is a pile of junk mail."
	.GSTR STR?128,"tru"
	.GSTR STR?164,"    "
	.GSTR STR?190,"With a towel wrapped around your head!?!"
WITH-TOWEL=STR?190
	.GSTR STR?257,"TAKE GOWN. PUT IT ON. OPEN THE POCKET. TAKE THE ANALGESIC."
	.GSTR STR?260,"Now you know what's going on outside."
	.GSTR STR?282,"At this point, listen to Ford and follow him to the Pub."
	.GSTR STR?320,"ON THE EARTH"
	.GSTR STR?342,"Try HEAR NOTHING or LISTEN TO DARKNESS."
	.GSTR STR?348,"At the fourth turn in Dark, one of your five senses will disappear."
	.GSTR STR?395,"Now you know what to type. Just wait around to hear the captain's poetry reading and see the question about what's going on in the Captain's Quarters."
	.GSTR STR?417,"At this point, brave men have been known to break down and cry."
	.GSTR STR?427,"Put the junk mail on the satchel, then press the button one last time."
	.GSTR STR?760,"AT THE PARTY"
	.GSTR STR?886,"Yes."
	.GSTR STR?33,"legend"
	.GSTR STR?46,"You lunge for it, but the room spins nauseatingly away. The floor gives you a light tap on the forehead."
	.GSTR STR?58,"I'm not convinced you're allowed to be playing with this computer."
	.GSTR STR?188,"I don't see what you're referring to."
REFERRING=STR?188
	.GSTR STR?255,"See the previous question."
	.GSTR STR?300,"Or BARTENDER, GIVE ME A CHEESE SANDWICH."
	.GSTR STR?319,"See the question about how much beer to drink."
	.GSTR STR?383,"See the Hitchhiker's Guide question in the General Questions section for more information."
	.GSTR STR?393,"See the question about the babel fish."
	.GSTR STR?431,"See the questions about the babel fish."
	.GSTR STR?433,"Why are the guards dragging me away?"
	.GSTR STR?434,"See the question about the gibberish from the intercom."
	.GSTR STR?486,"See the question about the missile attack at the end of this section."
	.GSTR STR?503,"See the question about the spare Improbability Drive."
	.GSTR STR?509,"See the question about controlling where you go when you leave Dark, in the section called ""In the Dark""."
	.GSTR STR?605,"See the question about the fluff."
	.GSTR STR?669,"See the question about the sandstone memorial."
	.GSTR STR?751,"See the previous questions in this section of the hint booklet."
	.GSTR STR?795,"You learn a lot about Ford's motivations, thus making for a more cohesive, internally consistent story line."
	.GSTR STR?843,"See the question about no tea in the General Questions section."
	.GSTR STR?954,"See the question about opening the hatch in the Heart of Gold section."
	.GSTR STR?966,"GENERAL QUESTIONS"
	.GSTR STR?1089,"SANTRAGINEAN MINERAL WATER"
	.GSTR STR?29,"ends"
	.GSTR STR?97,"irb"
	.GSTR STR?115,"zit"
	.GSTR STR?125,"huv"
	.GSTR STR?142," and life in the Universe has to carry on without you."
	.GSTR STR?143," and ... well, do you really want to know the rest? The point is that you have died."
	.GSTR STR?152," and pulls you into a corner. Days later, you expire from thirst and exhaustion."
	.GSTR STR?157,"""President Beeblebrox is a Swell Guy"" (Footnote 15)."
	.GSTR STR?206,"""Oh...you're trying to figure that out also? The manual's not much help, is it? By the way, do you know your score? I don't. My computer doesn't have a status line."""
ASK-ABOUT-OBJECT=STR?206
	.GSTR STR?209," You're getting close, though."
GETTING-CLOSE=STR?209
	.GSTR STR?222," the legendary lost planet of Magrathea"
LOST-PLANET=STR?222
	.GSTR STR?232," the manual override receptacle"
MOP=STR?232
	.GSTR STR?304,"You might return to survey the rubble, or to have it out with Prosser."
	.GSTR STR?498,"Still having trouble getting tea? See the question about the missile attack. It's the last question in this section."
	.GSTR STR?599,"You must give him the proper tool or you've blown your one chance to get the hatchway open."
	.GSTR STR?631,"You must find a way to prevent yourself from seeing the Beast. The Beast will then decide that since you can't see it, it can't see you!"
	.GSTR STR?644,"Still stuck? Go on to the next question."
	.GSTR STR?698,"You might try smiling, or waving, or making a speech."
	.GSTR STR?793,"You may find out more about the dog later."
	.GSTR STR?822,"You must become Ford Prefect first."
	.GSTR STR?1047,"pushing the red button on the Thumb when an Engineer robot is already present?"
	.GSTR STR?1071,"GALAXIA WOONBEAM"
	.GSTR STR?1103,"FN# HOW TO GET IT"
	.GSTR STR?151,"You notice the hostess approaching, but, using several mingling couples as cover, you maneuver away."
	.GSTR STR?170,"The air becomes thick with photon beams."
	.GSTR STR?214,"You notice the Beast's Lasero-Zap eyes, its Swivel Shear Teeth, and its several dozen tungsten carbide Vast-Pain claws, forged in the sun furnaces of Zangrijad. It has skin like a motorway and breath like a 747."
BEAST-DESC=STR?214
	.GSTR STR?247,"Why can't I pick things up?"
	.GSTR STR?279,"Should I go with Ford to the Pub?"
	.GSTR STR?404,"You need to block the small hole."
	.GSTR STR?432,"The announcement will begin 18 turns after you enter the Vogon Hold, or 3 turns after you obtain the babel fish."
	.GSTR STR?460,"Listen to Ford."
	.GSTR STR?466,"That you should be picked up in the vast emptiness of space by a ship inhabited by an acquaintance from your now destroyed native planet as well as your travelling companion's semi-cousin, can only be considered highly improbable. But then, with Infinite Improbability Drives at work, the infinitely improbable is not only possible but quite likely."
	.GSTR STR?552,"That still leaves the drive's large plug unattached. See the question about the controls on the Bridge."
	.GSTR STR?620,"That didn't work? Have you examined the spare Drive and the control console on the Bridge?"
	.GSTR STR?678,"Who am I?"
	.GSTR STR?690,"The autopilot doesn't seem concerned about your situation, since it just takes a look around and then shuts itself off."
	.GSTR STR?691,"You need to give the autopilot some impetus to go to work."
	.GSTR STR?750,"That item is the unsightly piece of jacket fluff."
	.GSTR STR?796,"Oh, right. You're more interested in puzzle solutions. The entire point of this scene is acquiring one particular item for use on the Heart of Gold."
	.GSTR STR?800,"That something is Arthur Dent."
	.GSTR STR?820,"You need to feed the dog back at the beginning of the game."
	.GSTR STR?928,"The ancient legend is of particular interest."
	.GSTR STR?952,"They don't really have much use..."
	.GSTR STR?1115,"12  This footnote is self referenced"
	.GSTR STR?30,"Biting"
	.GSTR STR?60,"No, no, a thousand times no. Go boil an egg."
	.GSTR STR?131,"w c"
	.GSTR STR?134,"i s"
	.GSTR STR?154,"The boat is gone."
	.GSTR STR?192,"The bulldozer piles into the side of your home."
BULLDOZER-PILES=STR?192
	.GSTR STR?198,"The battle fleet plunges toward Earth and"
FLEET-PLUNGES=STR?198
	.GSTR STR?204," Thumb merely makes a few feeble clicking noises."
THUMB-CLICKS=STR?204
	.GSTR STR?219,"The barman snaps ""Hands off until you pay for it!"""
HANDS-OFF=STR?219
	.GSTR STR?227," Slowly it dawns on the creature that someone is trying to make a fool of it. It starts to look for you again."
SLOWLY-DAWNS=STR?227
	.GSTR STR?254,"You'll have to get rid of it."
	.GSTR STR?272,"You'll have to wait a few turns after you lie down before the bulldozer finally grinds to a halt."
	.GSTR STR?317,"Why do I die during transference?"
	.GSTR STR?358,"Tea is a better source of Brownian Motion for the Improbability Drive than the Advanced Tea Substitute (ATS). Try it."
	.GSTR STR?366,"If seeing is the missing sense: When the light stabs at the ""front"" of your eyes, then your exit is the Country Lane. When it's at the ""back"" of your eyes, then you go onto the Presidential Speedboat."
	.GSTR STR?374,"Why do I get groggy and die?"
	.GSTR STR?387,"You'll have to get the babel fish on your own."
	.GSTR STR?398,"Why does the machine go ""click""?"
	.GSTR STR?409,"You'll have to block the drain."
	.GSTR STR?477,"Are the Bridge controls useful?"
	.GSTR STR?524,"You'll be able to find the Nutrimat/Computer Interface elsewhere in the game."
	.GSTR STR?533,"You'll have to argue with the game for a few turns."
	.GSTR STR?540,"You'll have to be persistent if you want to find out what's in the Engine Room."
	.GSTR STR?544,"You'll need the atomic vector plotter from the Vogon Hold. If you never got it while you were aboard the Vogon ship, you'll have to start the game over or go back to a saved position."
	.GSTR STR?545,"You'll also need a good source of Brownian Motion."
	.GSTR STR?548,"You'll need the cup of Advanced Tea Substitute (ATS), which you can get from the Nutrimat in the Galley."
	.GSTR STR?571,"You'll have to make yourself very happy before entering."
	.GSTR STR?593,"You'll have to figure out how to override Eddie's wishes by fixing the hatchway mechanism in the Access Space."
	.GSTR STR?616,"You'll have to save the ship yourself."
	.GSTR STR?637,"Why does the beast ask me my name?"
	.GSTR STR?658,"Are the tall walls important?"
	.GSTR STR?663,"Are the bleached bones important?"
	.GSTR STR?668,"Are the sharp stones important?"
	.GSTR STR?957,"Flathead screwdriver: in your Bedroom. Toothbrush: in your Bedroom. Tweezers: inside Trillian's handbag. Molecular hyperwave pincer: on the Bridge. Ionic diffusion rasp: in the Engine Room. Hypersonic pliers: in the Engine Room. Thermo-fusion chisel: in Marvin's Pantry. Laser-assisted monkey wrench: inside the toolbox on the speedboat. Ultra-plasmic vacuum awl: in the War Chamber. Number twelve asteroid paint chipper: you're holding it when you return from your adventure at the end of the Traal scene."
	.GSTR STR?965,"You obviously didn't read your manual very carefully. That's explained in the section entitled Important Commands."
	.GSTR STR?1015,"opening the hatch in the Heart of Gold before landing on Magrathea?"
	.GSTR STR?7,"This is a small closet with an exit to starboard."
	.GSTR STR?16,"This is an entry bay for the Heart of Gold. A corridor lies aft of here."
	.GSTR STR?28,"begins"
	.GSTR STR?38,"Knocking on"
	.GSTR STR?51,"What a concept."
	.GSTR STR?65,"This is the enclosed front porch of your home. Your front garden lies to the south, and you can reenter your home to the north."
	.GSTR STR?139,"This airlock has massive doors to port and starboard."
	.GSTR STR?144,"This is the heart of the Beast's lair. The only exit leads northeast."
	.GSTR STR?146,"This is part of a spongy gray maze of twisty little synapses, all alike."
	.GSTR STR?224,"The crowd cheers wildly! It thinks you're terrific."
CROWD-CHEERS=STR?224
	.GSTR STR?273,"What should I do with Ford Prefect?"
	.GSTR STR?281,"This will happen if you wait a few turns after Ford shows up."
	.GSTR STR?283,"What should I do in the Pub?"
	.GSTR STR?305,"What should I do about the dog?"
	.GSTR STR?340,"This time, though, it isn't smell that goes away on the fourth description."
	.GSTR STR?375,"This is caused by your protein loss during the matter transference beams."
	.GSTR STR?396,"What is the tall dispensing machine?"
	.GSTR STR?400,"What is a babel fish?"
	.GSTR STR?401,"Consult the Guide."
	.GSTR STR?436,"What happens in Captain's Quarters?"
	.GSTR STR?441,"This poetry is painfully awful. Have you tried to STOP THE POETRY or COVER MY EARS or DON'T LISTEN TO THE VOGON POETRY."
	.GSTR STR?455,"Apparently, there's another spaceship nearby. Try hitchhiking by pressing the green button."
	.GSTR STR?456,"This sends you through a matter transference beam, and you find yourself in the Dark again."
	.GSTR STR?471,"Is Eddie, the ship computer, of use?"
	.GSTR STR?499,"What is the Advanced Tea Substitute?"
	.GSTR STR?546,"Consult the Hitchhiker's Guide about Brownian Motion."
	.GSTR STR?554,"This is a very difficult problem."
	.GSTR STR?583,"What puzzles or obstacles still remain that he might help with?"
	.GSTR STR?614,"This is a good point for a SAVE."
	.GSTR STR?615,"The computer is helpless because you've tied it up with the Nutrimat interface."
	.GSTR STR?617,"The computer is tied up, so it can't turn on the main Drive during this emergency."
	.GSTR STR?645,"What use is the sandstone memorial?"
	.GSTR STR?694,"What do I do when the boat docks?"
	.GSTR STR?696,"What do I do when I reach the Dais?"
	.GSTR STR?700,"What do I do about the Guards?"
	.GSTR STR?711,"This isn't helpful all by itself, since the guards pick up their rifles and still shoot you if you break for the ship."
	.GSTR STR?725,"This is the Party where Arthur Dent tried to pick up Tricia MacMillan (but, you'll recall, failed completely)."
	.GSTR STR?727,"What should I do about Phil?"
	.GSTR STR?731,"The cage is hiding Phil's second head."
	.GSTR STR?735,"What should I do about Arthur?"
	.GSTR STR?740,"What should I do about the hostess?"
	.GSTR STR?772,"What did Ford do at this point when you were Arthur?"
	.GSTR STR?775,"What should I do about Prosser?"
	.GSTR STR?789,"Then DRINK THE BEER. Arthur will follow your example. You need to do this twice."
	.GSTR STR?802,"This is a rather weird action, and Arthur won't accept the fluff until he's had enough beer."
	.GSTR STR?812,"Then solve the puzzle involving the giant dog."
	.GSTR STR?817,"This is the very same dog you ran into in the Country Lane back at the beginning of the game."
	.GSTR STR?838,"What is this black particle for?"
	.GSTR STR?889,"What is the thing my aunt gave me?"
	.GSTR STR?895,"This is useful for transporting more objects than you can carry, but it isn't ever necessary to do so."
	.GSTR STR?933,"A list of all four fluff, and their locations, follows. You shouldn't look at this list unless you're completely stumped, because it will give away a lot."
	.GSTR STR?941,"What do I do about the plant?"
	.GSTR STR?950,"What are all these tools for?"
	.GSTR STR?956,"A list of all ten, and their locations, follows. You shouldn't look at this list unless you're completely stumped, because it will give away a lot."
	.GSTR STR?958,"What is the goal of the game?"
	.GSTR STR?968,"This section should only be used as a last resort, or for your own interest after you've completed the game."
	.GSTR STR?1069,"FRANCE"
	.GSTR STR?68,"Arthur"
	.GSTR STR?80,"Arthur Dent is here."
	.GSTR STR?81,"Arthur exclaims"
	.GSTR STR?88,"computers."
	.GSTR STR?90,"The door to the corridor is locked (from the outside)."
	.GSTR STR?106,"d t"
	.GSTR STR?114,"u n"
	.GSTR STR?118,"qui"
	.GSTR STR?354,"Not usually."
	.GSTR STR?473,"Eddie is the only one who can turn on the main drive."
	.GSTR STR?475,"Eddie's help is indirectly necessary to obtain a cup of tea."
	.GSTR STR?591,"Eddie (the shipboard computer) jammed the hatch to prevent anyone from leaving the ship until he's checked to make sure the environment is safe."
	.GSTR STR?667,"Black paint? There's no black paint. You're looking at answers you shouldn't be."
	.GSTR STR?730,"The draped cage on his shoulder does NOT contain a bird."
	.GSTR STR?736,"Arthur keeps trying to start a conversation with you, but he's too shy and embarrassed. If you try to talk to him, he finds your tone rather cool, and moves away."
	.GSTR STR?785,"Arthur is now willing to follow you to the Pub."
	.GSTR STR?801,"Give the fluff to Arthur."
	.GSTR STR?814,"The dog really isn't a giant dog."
	.GSTR STR?818,"The dog swallows the space fleet for one particular reason."
	.GSTR STR?1060,"GUIDE ENTRIES"
	.GSTR STR?1078,"INTELLIGENCE"
	.GSTR STR?61,"Complete waste of time."
	.GSTR STR?112,"ulp"
	.GSTR STR?169,"Done."
	.GSTR STR?172," of five turns ago suddenly materialises inside your brain. There is an incredibly nasty, cracking, scrunching noise, and blood and bone fly everywhere as your head, to be perfectly frank about this, explodes. We did warn you."
	.GSTR STR?229,"finite Improbability Generator"
FIG=STR?229
	.GSTR STR?297,"At least, not when you're Arthur."
	.GSTR STR?364,"For example, when smell disappears, type SMELL DARK. If the object is ""being waved,"" then the exit leads to the Vogon Hold. If the object is ""waving,"" the exit is the Lair of the Ravenous Bugblatter Beast of Traal."
	.GSTR STR?365,"When hearing is missing: If the sound is ""far above you,"" then your exit is Entry Bay Number Two of the Heart of Gold. If it's ""far below you,"" then it's the War Chamber of the battle fleet."
	.GSTR STR?367,"When feel is missing: If it feels ""cold"" and wet and squishy, the exit is to the Living Room party. When it's ""warm,"" your exit is into the sperm whale."
	.GSTR STR?368,"When you are controlling dark and have determined your current exit, but you don't want to go there, simply WAIT and you will get a new missing sense. NOTE: You will never get the whale exit unless you are using real tea for your Brownian Motion source."
	.GSTR STR?419,"When you placed the satchel in front of the panel, the satchel is now LYING ON ITS SIDE in front of the panel."
	.GSTR STR?426,"When the upper-half-of-the-room cleaning robot grabbed the babel fish the first time it said that the fish was ""the only flying junk"" that the robot found."
	.GSTR STR?442,"When he finishes the first verse the Captain says, ""You didn't look like you enjoyed my poetry at all!"" and then has you thrown into space."
	.GSTR STR?446,"For example, if the recording asked you to type the second word from the second verse, and the word was ""lyshus,"" you should type TYPE ""LYSHUS"" when you get back to the Vogon Hold. NOTE: Each time you play the game, the lines of the second verse come in different orders. Similarly, the glass case's recording asks for a different number word each time you play."
	.GSTR STR?484,"When you use the drive while it's plugged into the large receptacle, both the large receptacle and the large plug are destroyed."
	.GSTR STR?580,"Before Marvin will perform his one task, you must get past the screening door near the aft end of the corridor."
	.GSTR STR?595,"Someone else does."
	.GSTR STR?675,"The entire point of this scene is to get that Nutrimat/Computer Interface."
	.GSTR STR?791,"When Arthur's house is destroyed, he will rush out of the Pub. It would be a good idea to stay with him."
	.GSTR STR?809,"Those two warring races have now set off on a quest for vengeance against the world (Earth) that spawned the person (you) whose remark set off their war."
	.GSTR STR?997,"to GET DRUNK in the pub?"
	.GSTR STR?1,"Not Here"
	.GSTR STR?136,"""Fripping lyshus wimbgunts, awhilst moongrovenly kormzibs."""
	.GSTR STR?207,"You struggle to reach the Thumb, but the wind is too fierce and you are driven back."
DRIVEN-BACK=STR?207
	.GSTR STR?349,"You should type the sense that no longer appears, such as SMELL or SEE."
	.GSTR STR?350,"The first time, smell will go away. See the first question in this section."
	.GSTR STR?415,"If it isn't bulky enough, the cleaning robot dashes around it."
	.GSTR STR?440,"You should now know that you have to listen to the second verse (not line) of the poem in order to get the atomic vector plotter."
	.GSTR STR?450,"You should have gotten the atomic vector plotter."
	.GSTR STR?493,"But first, you'll need something that isn't in the Galley."
	.GSTR STR?589,"If sirens and lights went off when you tried to open the hatch, then the ship is still in space. Wait until the ship has landed."
	.GSTR STR?619,"Turn on the spare Drive."
	.GSTR STR?705,"You should say GUARDS, DON'T SHOOT or GUARDS, DROP THE PHOTON RIFLES."
	.GSTR STR?770,"You shouldn't be in the Pub at this point."
	.GSTR STR?771,"According to the introductory text for this scene, why did you come here?"
	.GSTR STR?784,"Try PROSSER, LIE DOWN IN FRONT OF THE BULLDOZER."
	.GSTR STR?788,"The first thing to do is BUY SOME BEER."
	.GSTR STR?847,"The first theory states that the particle is too small to see when you recover from being microscopic."
	.GSTR STR?851,"You should be able to figure it out for yourself."
	.GSTR STR?854,"The first goal is to get the awl."
	.GSTR STR?907,"You should read the Guide entry on the Thumb."
	.GSTR STR?916,"The first is near the beginning of the game, when you use it to get to the Vogon ship."
	.GSTR STR?937,"You should plant each piece of fluff in the flowerpot."
	.GSTR STR?991,"You shouldn't develop anything in this section until you've finished the game. Things in the section will invariably give away the answers to puzzles in the game."
	.GSTR STR?1026,"to CARVE NAME ON MEMORIAL (rather than CARVE MY NAME ON MEMORIAL)?"
	.GSTR STR?1036,"jumping into the water from the Presidential Speedboat?"
	.GSTR STR?1087,"RAVENOUS BUGBLATTER BEAST OF TRAAL"
	.GSTR STR?96,"r g"
	.GSTR STR?177,"It goes down well."
DOWN-WELL=STR?177
	.GSTR STR?248,"Are you out of the bed with the light on?"
	.GSTR STR?258,"Is the pile of mail important?"
	.GSTR STR?425,"Is there an object that when flung into the air might act as many items?"
	.GSTR STR?435,"The guards will arrive 36 turns after you arrive in the Vogon Hold, or 5 turns after you obtain a babel fish."
	.GSTR STR?504,"Is the cup of tea important?"
	.GSTR STR?520,"Is the shipping carton important?"
	.GSTR STR?525,"Is the strange gun important?"
	.GSTR STR?530,"The gun is completely worthless, useless, and unimportant."
	.GSTR STR?538,"The game claims that there's nothing interesting there."
	.GSTR STR?542,"Is the spare Drive important?"
	.GSTR STR?608,"The glimpse of the future provided by the fruit tells you what tool to bring into the Access Space."
	.GSTR STR?703,"The guards don't know that you're planning to steal the Heart of Gold, so they're on your side."
	.GSTR STR?713,"The guards will NOT leave the scene, no matter what you do."
	.GSTR STR?830,"Ah, but whose brain?"
	.GSTR STR?856,"WAR CHAMBER/MAZE"
	.GSTR STR?885,"Is there a significance to ""no tea""?"
	.GSTR STR?899,"Is the Hitchhiker's Guide important?"
	.GSTR STR?1062,"ALCOHOL"
	.GSTR STR?47,"You're certainly picking the tough tasks. The floor acts like a trampoline on an ice rink, or like something they've been working on for years at Disneyland."
	.GSTR STR?84,"how badly Americans make tea."
	.GSTR STR?149,"The hostess, a lethally dull woman, corners you and bores you to death. Literally."
	.GSTR STR?215,"You're not holding"
NOT-HOLDING=STR?215
	.GSTR STR?234," you've been trying to get rid of it for years."
GET-RID=STR?234
	.GSTR STR?335,"That's your way out of Dark."
	.GSTR STR?381,"That's the Hitchhiker's Guide to the Galaxy."
	.GSTR STR?474,"But he won't obey your order to do that, only Zaphod's."
	.GSTR STR?610,"You're now awesomely close to the end of the game."
	.GSTR STR?677,"ON TRAAL"
	.GSTR STR?681,"You're on Damogran. If you'd like to know more about it, consult the Hitchhiker's Guide."
	.GSTR STR?697,"You're here for the dedication ceremonies of the Heart of Gold. You obviously have the crowd eating out of your hands."
	.GSTR STR?702,"Trillian isn't really attacking you. It's just part of your plan to steal the Heart of Gold."
	.GSTR STR?704,"You're President of the Galaxy! The guards will probably listen to your orders."
	.GSTR STR?741,"You're usually able to avoid her."
	.GSTR STR?781,"But he can't hear you from here."
	.GSTR STR?829,"You're inside a brain."
	.GSTR STR?857,"You're still Arthur in this scene."
	.GSTR STR?858,"You're inside a sperm whale, obviously."
	.GSTR STR?881,"Isn't it obvious?"
	.GSTR STR?1016,"kicking the screening door, then entering Marvin's Pantry?"
	.GSTR STR?1034,"throwing the glass of wine or the plate of hors d'oeuvres?"
	.GSTR STR?1037,"throwing something into the water from the boat?"
	.GSTR STR?1040,"examining the approaching star system and the third planet from the War Chamber of the battle fleet?"
	.GSTR STR?1108," 5  Remove the towel (beast asleep)"
	.GSTR STR?63,"A totally unhelpful idea."
	.GSTR STR?86,"a recent visit to Tiverton."
	.GSTR STR?94,". You, however, are blasted into tiny bits and smeared all over the room. Several cleaning robots fly in and wipe you neatly off the walls."
	.GSTR STR?179,"(We were lying about the exit to port.) "
LYING-ABOUT-EXIT=STR?179
	.GSTR STR?182,"Look around you."
LOOK-AROUND=STR?182
	.GSTR STR?333,"Try SMELL THE DARKNESS or SMELL NOTHING or even just SMELL."
	.GSTR STR?457,"Both methods of surviving the Airlock are equivalent."
	.GSTR STR?476,"But in terms of solving puzzles, you can basically ignore Eddie."
	.GSTR STR?622,"Note that when the spare Drive is NOT connected to the control console and you turn it on, the effect is always directed at you personally. When the spare Drive IS connected to the console, activating it has an effect on the entire ship."
	.GSTR STR?674,"Go southwest from the Lair."
	.GSTR STR?756,"Look at what you're carrying again."
	.GSTR STR?846,"Particle physicists have two theories on what happened to the particle."
	.GSTR STR?859,"Note the sound of rushing air."
	.GSTR STR?914,"To do so, push the red button to summon a repair robot. See the following question for further details on repairing the Thumb."
	.GSTR STR?971,"    5  Drinking the beer (1st time)"
	.GSTR STR?972,"    5  Drinking the beer (2nd time)"
	.GSTR STR?973,"    5  Drinking the beer (3rd time)"
	.GSTR STR?1000,"petting or kicking the dog?"
	.GSTR STR?1030,"showing the thing your aunt gave you to the Beast?"
	.GSTR STR?1082,"MATTER TRANSFERENCE BEAMS"
	.GSTR STR?1116,"13  Push the autopilot button thrice"
	.GSTR STR?20,"Everything becomes dark! But no, not quite everything ... There's a big bright planet below, just visible behind your mighty tail fin. Air begins rushing by, tickling your snout and dorsal fins ... you suddenly realise that, improbably enough, you've turned yourself into a sperm whale and are plummeting through the atmosphere of a planet! You begin experimenting with your new body, opening and closing your spout and wagging your enormous tail. Just as you are getting used to being a whale, the ground rushes up and hits you at about 200 mph."
	.GSTR STR?40,"Pushing"
	.GSTR STR?105,"vup"
	.GSTR STR?262,"What's that bulldozer doing outside?"
	.GSTR STR?315,"You want to hitch a ride aboard one of the Vogon ships."
	.GSTR STR?334,"What's this shadow I see?"
	.GSTR STR?380,"What's this Guide Ford gives me?"
	.GSTR STR?428,"What's the gibberish I hear?"
	.GSTR STR?551,"You want to plug the small plug (from the drive) into the small receptacle (in the atomic vector plotter). Put the plotter's long dangly bit into the cup of ATS."
	.GSTR STR?576,"Until a point, he won't do anything you tell him to do."
	.GSTR STR?586,"You want to order Marvin to open the hatch (as in MARVIN, OPEN THE HATCH). See the question about opening the hatch for more information."
	.GSTR STR?651,"You want to carve your name in the memorial, as in CARVE MY NAME ON THE SANDSTONE MEMORIAL."
	.GSTR STR?670,"What's the point of the Traal scene?"
	.GSTR STR?708,"Until Trillian shows up, the game won't even let you try."
	.GSTR STR?718,"What's the point of Damogran?"
	.GSTR STR?748,"What's the point of the party scene?"
	.GSTR STR?752,"You want to get ""picked up"" by Phil. However, he won't take any notice of you until you take the fluff and get Arthur talking to you."
	.GSTR STR?765,"You want to do what Ford did when you were Arthur."
	.GSTR STR?777,"You want Arthur to come with you to the Pub."
	.GSTR STR?779,"He won't stand up until you've safeguarded his house."
	.GSTR STR?783,"You want him to lie down in front of the bulldozer."
	.GSTR STR?794,"What's the point of this scene?"
	.GSTR STR?805,"What's going on in the War Chamber?"
	.GSTR STR?850,"What's the point of this section?"
	.GSTR STR?880,"What's the point of the whale?"
	.GSTR STR?884,"INSIDE THE WHALE"
	.GSTR STR?925,"What's this nonsense about fluff?"
	.GSTR STR?977,"   25   Opening the glass case"
	.GSTR STR?978,"   25   Entering the Engine Room"
	.GSTR STR?979,"   25   Getting the Interface"
	.GSTR STR?981,"   25   Leaving the party with Phil"
	.GSTR STR?982,"   25   Stealing the Heart of Gold"
	.GSTR STR?983,"   25   Taking the black particle"
	.GSTR STR?985,"   25   Entering Marvin's Pantry"
	.GSTR STR?986,"   25   Blooming the plant"
	.GSTR STR?987,"   25   Get Marvin to open the hatch"
	.GSTR STR?1019,"smashing the circuit board?"
	.GSTR STR?1045,"wrapping the towel around your head anywhere except Traal?"
	.GSTR STR?1094,"THUMB"
	.GSTR STR?1101,"FOOTNOTES"
	.GSTR STR?32,"gun"
	.GSTR STR?70,"Prosser"
	.GSTR STR?87,"a new book by Douglas Adams."
	.GSTR STR?191,"A brave, Zen-like effort. It fails."
ZEN=STR?191
	.GSTR STR?201," in a cloud of green, sweet-smelling steam. "
CLOUD-OF-STEAM=STR?201
	.GSTR STR?225,"Humans are so depressingly "
HUMANS=STR?225
	.GSTR STR?491,"Actually, there is a way to get something else from the Nutrimat."
	.GSTR STR?579,"He always disappears through a certain door."
	.GSTR STR?722,"ON DAMOGRAN"
	.GSTR STR?924,"Actually, you can shortcut by showing the guarantee first."
	.GSTR STR?934,"Pocket fluff: in the pocket of your gown at the start of the game. Satchel fluff: inside Ford's satchel (see EARTH, REVISITED). Jacket fluff: on Arthur's jacket (see AT THE PARTY). Seat cushion fluff: under the pilot seat of the speedboat (see ON DAMOGRAN)."
	.GSTR STR?947,"Carry the plant into the sauna."
	.GSTR STR?1099,"various tools"
	.GSTR STR?1100,"various weapons"
	.GSTR STR?2,"Actor"
	.GSTR STR?104,"a r"
	.GSTR STR?174," is certainly a shock to the system. Too bad you didn't consume enough alcohol to withstand it."
	.GSTR STR?212,"Just as the Beast is trying to work out where you've disappeared to, it "
JUST-AS=STR?212
	.GSTR STR?285,"Why not do as he says?"
	.GSTR STR?323,"You've been through a matter transference beam, and still haven't recovered from the shock of it."
	.GSTR STR?339,"You've been through Dark at least once before, so you know what's going on."
	.GSTR STR?443,"Why not relax and enjoy it?"
	.GSTR STR?462,"You've just been picked up by a fantastic new spaceship powered by something called an Infinite Improbability Drive. Find out more about the drive."
	.GSTR STR?479,"The large receptacle is important."
	.GSTR STR?481,"The large plug from the spare Drive can be plugged into the large receptacle."
	.GSTR STR?508,"Because it has even more Brownian Motion than the ATS, it will make a better source of it for the spare Improbability Drive. Try it."
	.GSTR STR?624,"THE HEART OF GOLD"
	.GSTR STR?692,"Instead of steering toward the channel, try steering toward the cliff or the rocky spire."
	.GSTR STR?811,"Just TAKE AWL!"
	.GSTR STR?879,"Just put the flowerpot inside the aunt's gift and then wait until the whale splats. Within a few turns after leaving Dark, the aunt's gift should reappear, containing the pot."
	.GSTR STR?891,"You've probably noticed that it keeps turning up."
	.GSTR STR?896,"Because of these two properties (auto-return and containment) the thing your aunt gave you provides an alternate solution of one of the puzzles in the game."
	.GSTR STR?974,"    8   Arriving at the Vogon Hold"
	.GSTR STR?1085,"PERIL-SENSITIVE SUNGLASSES"
	.GSTR STR?14,"Phil is here."
	.GSTR STR?15,"Phil comes up and grips your shoulder. ""Hey babe, this guy boring you? Why not come with me instead? I'm from a different planet."" He takes you out to the parking lot, where his flashy interorbital ion scooter is parked between two Volkswagens. After mounting it, the scooter accelerates at such a great speed that you black out almost immediately."
	.GSTR STR?18,"39,745"
	.GSTR STR?103,"flu"
	.GSTR STR?120,"kon"
	.GSTR STR?173,"bottle"
	.GSTR STR?205," Brownian motion"
BROWNIAN=STR?205
	.GSTR STR?316,"PUSH THE GREEN BUTTON."
	.GSTR STR?465,"The man is Zaphod Beeblebrox, current President of the Galaxy, who has stolen this revolutionary new Infinite Improbability Drive-powered spaceship in order to locate the legendary lost planet of Magrathea. Zaphod and Ford know each other."
	.GSTR STR?689,"PUSH THE AUTOPILOT BUTTON."
	.GSTR STR?726,"Thanks to the wild vagaries of Improbability Physics, you have not only travelled back in time, you have changed your identity as well."
	.GSTR STR?732,"Phil is actually Zaphod Beeblebrox in disguise. He has undoubtedly dropped by this Islington party as part of some interstellar party-crashing hop."
	.GSTR STR?823,"During the scene where you're Ford, buy a sandwich, then give the sandwich to Arthur. When Arthur dashes out of the Pub, he'll feed the sandwich to the dog."
	.GSTR STR?877,"For more details, see the question on getting out of the whale."
	.GSTR STR?940,"For more information, see the next question."
	.GSTR STR?1064,"BABEL FISH"
	.GSTR STR?101,"p w"
	.GSTR STR?108,"tha"
	.GSTR STR?123,"gry"
	.GSTR STR?140," into you."
	.GSTR STR?231,"standing on the other side"
ON-OTHER-SIDE=STR?231
	.GSTR STR?237," RETURN = See hint"
	.GSTR STR?243," RETURN = See topics"
	.GSTR STR?324,"Recovery takes time..."
	.GSTR STR?532,"Yes, but not without a fight."
	.GSTR STR?534,"Usually, YES or NO responses are sufficient."
	.GSTR STR?570,"Did you die upon passing through the screening door? It's because Marvin lives in the room beyond the door, and his awesome depression pervades the place."
	.GSTR STR?575,"Yes, but not right away."
	.GSTR STR?739,"Did you notice that you can't take the fluff until you drop one of the other things you're carrying (handbag, wine, hors d'oeuvres)? You can't hold more than three things while you're at the party."
	.GSTR STR?116,"z z"
	.GSTR STR?117,"eft"
	.GSTR STR?138,"""Bleem miserable venchit! Bleem forever mestinglish asunder frapt."""
	.GSTR STR?178,"It's not plugged into anything!"
NOT-PLUGGED=STR?178
	.GSTR STR?183,"It's too dark to see!"
TOO-DARK=STR?183
	.GSTR STR?200," black jewelled battle shorts, "
BATTLE-SHORTS=STR?200
	.GSTR STR?239,"INVISICLUES (tm)"
	.GSTR STR?251,"It's the gown."
	.GSTR STR?264,"It's there to knock down your house to make way for a new highway bypass."
	.GSTR STR?310,"Read everything carefully."
	.GSTR STR?328,"Read carefully."
	.GSTR STR?330,"Read each response to WAITing in the Dark very carefully."
	.GSTR STR?336,"EXAMINE THE SHADOW."
	.GSTR STR?341,"It's hearing."
	.GSTR STR?360,"For one thing, a sense is missing right away, rather than after three WAITs."
	.GSTR STR?361,"More importantly, with tea, a different sense will be missing each time you WAIT. Thus, you can ""control Dark."""
	.GSTR STR?377,"It's something that Ford just gave you."
	.GSTR STR?378,"It's frequently found on shelves behind bars in Pubs."
	.GSTR STR?382,"It's the single most useful thing an intergalactic hitchhiker (or Infocom game player) can have."
	.GSTR STR?391,"Well, perhaps that wasn't such a great idea. Try flipping the switch."
	.GSTR STR?399,"It's out of fish. Time to RESTORE."
	.GSTR STR?429,"It's an announcement in Vogonese."
	.GSTR STR?461,"Read the sales brochure that's in the Entry Bay."
	.GSTR STR?468,"From the Bridge, walk to port."
	.GSTR STR?490,"Well, maybe not so delicious. But at least useful."
	.GSTR STR?492,"It's a cup of tea (REAL tea, not ATS)."
	.GSTR STR?543,"Read the Guide entry on Improbability Physics."
	.GSTR STR?557,"Presumably you've tried OPEN THE DOOR."
	.GSTR STR?559,"Read the Guide entry on INTELLIGENCE."
	.GSTR STR?582,"Congratulations. You've now impressed Marvin enough for him to listen to one request from you. Do you have any idea what order to give him?"
	.GSTR STR?634,"It's something important, which no interstellar hitchhiker should ever be without."
	.GSTR STR?653,"It's not any of the tools."
	.GSTR STR?654,"It's something found on Traal."
	.GSTR STR?688,"EXAMINE THE CONTROLS."
	.GSTR STR?769,"Obviously, you're doing the wrong thing."
	.GSTR STR?797,"It's in the satchel."
	.GSTR STR?798,"It's the satchel fluff."
	.GSTR STR?815,"It's a normal-sized dog. The spaceship you're aboard is microscopic."
	.GSTR STR?866,"It's a method you've used before."
	.GSTR STR?871,"No matter what you do, you've only got ten moves in the whale before it splats."
	.GSTR STR?875,"The other method involves the thing your aunt gave you which you don't know what it is."
	.GSTR STR?883,"The only point of this scene is to get the flowerpot."
	.GSTR STR?887,"It's a hint that at some point, getting tea will be important."
	.GSTR STR?897,"It's a puzzle toward the very end of the game."
	.GSTR STR?898,"It's the puzzle of getting the flowerpot out of the whale."
	.GSTR STR?900,"Well, the game IS named after it..."
	.GSTR STR?944,"Read the Guide entry on fluff again."
	.GSTR STR?1066,"DAMOGRAN"
	.GSTR STR?1080,"LONG DANGLY BIT"
	.GSTR STR?141,"Suddenly, a team of Fronurbdian Beasthunters charges in, intent on catching the Beast for their zoo. Mistaking you for the Beast, they fire stun guns at you, wrap you in nets, and install you in a lovely little lair in the Fronurbdi National Zoo.

Three months later the error is discovered, but while your damage suit is pending in the Fronurbdian courts the planet is invaded by Bureaucratic Pirates from Pallidon IV. Impressed into bondage for a 16-year filing and sorting mission on the so-called ""basement world"" of Sporla in the Lesser Magellanic Cloud, you escape with the help of a tribe of nomadic asteroid painters.

You develop a unique talent for asteroid painting, gaining considerable fame throughout the Cloud. A nickel-ore deluxe is commissioned by His Royal Gorpness Orbjfelk, the ruler of the Nine Hundred Worlds of Gorp, but while working on this new masterpiece your asteroid slips into a small passing black hole."
	.GSTR STR?238,"Q = Main menu"
	.GSTR STR?261,"Take it along, it might prove useful later."
	.GSTR STR?424,"Unfortunately, there's only room for one object on the satchel."
	.GSTR STR?459,"Who picked us up hitchhiking?"
	.GSTR STR?535,"The proper sequence, from the Corridor, Aft End is AFT. YES. YES. AFT. NO."
	.GSTR STR?611,"Go down through the hatch."
	.GSTR STR?636,"Unfortunately, you can't move around very well with a towel over your eyes. Furthermore, as you may have already noticed, this method is also only temporarily effective."
	.GSTR STR?638,"A good question. Have you tried figuring out the answer yourself?"
	.GSTR STR?662,"Unfortunately, you can't do any of the above."
	.GSTR STR?716,"Take the blaster from Trillian and shoot the rifles. Alternatively you can just ASK TRILLIAN TO SHOOT THE PILE OF RIFLES."
	.GSTR STR?840,"The particle is your own common sense!"
	.GSTR STR?849,"Take your pick."
	.GSTR STR?902,"The proper syntax for reading a particular Guide entry is CONSULT GUIDE ABOUT (item). For example, you could type CONSULT GUIDE ABOUT MUSHROOMS."
	.GSTR STR?953,"...until the very end of the game."
	.GSTR STR?996,"asking Prosser for the time?"
	.GSTR STR?1004,"asking PROSSER, WHAT ABOUT MY HOME after it's been demolished?"
	.GSTR STR?1013,"asking FORD, WHAT ABOUT THE EARTH once it's been destroyed?"
	.GSTR STR?1022,"asking Eddie to open the hatch after the ship has landed?"
	.GSTR STR?1024,"saying something other than your name when the Beast asks for it?"
	.GSTR STR?1025,"saying your name with the towel over your eyes?"
	.GSTR STR?1059,"asking various characters about the object of the game? (Especially Prosser, Ford, Marvin, Eddie, the Nutrimat, the screening door, and the Beast.)"
	.GSTR STR?1113,"10  Looking in the Engine Room"
	.GSTR STR?1119,"MISCELLANEOUS"
	.GSTR STR?218,"""Announcement, announcement. This is "
ANNOUNCEMENT=STR?218
	.GSTR STR?271,"BLOCK THE BULLDOZER, STOP THE BULLDOZER, or LIE DOWN also work."
	.GSTR STR?299,"How about BUY A CHEESE SANDWICH."
	.GSTR STR?301,"Perhaps ASK BARTENDER FOR A SANDWICH is more up your alley."
	.GSTR STR?345,"Perhaps AFT would be more productive, come to think of it."
	.GSTR STR?607,"Eat the fruit."
	.GSTR STR?628,"The Beast will devour you about five turns after you pop up in its Lair."
	.GSTR STR?643,"The Beast's response when you told it your name should provide an additional hint toward why the Beast wants to know your name and how to solve this entire Traal puzzle."
	.GSTR STR?647,"The Beast wants to carve your name in this, his memorial of remembrance, after he has devoured you."
	.GSTR STR?969,"SCORE  ACTION"
	.GSTR STR?989,"NOTE: You LOSE 30 points each for eating the cheese sandwich, drinking the Advanced Tea Substitute, or turning on the spare Drive while plugged into the large receptacle before the missile attack begins."
	.GSTR STR?1072,"GENUINE PEOPLE PERSONALITIES"
	.GSTR STR?1074,"HEART OF GOLD"
	.GSTR STR?3,"M-Beg"
	.GSTR STR?37,"Kicking"
	.GSTR STR?43,"Shaking"
	.GSTR STR?69,", which you may have noticed outside, just pushed your home down on top of you."
	.GSTR STR?75,", due to a terrible miscalculation in scale, is swallowed by a small dog."
	.GSTR STR?107,"imb"
	.GSTR STR?135,"The Captain is indescribably hideous, indescribably blubbery, and indescribably mid-to-dark green. He is holding samples of his favourite poetry."
	.GSTR STR?156,"The remnants of a rapidly dispersing crowd gasp at your appearance. You are immediately seized by guards who, in an unconstitutional departure from protocol, hurl you over the cliff."
	.GSTR STR?168,"F"
	.GSTR STR?249,"The room is spinning because you have a hangover."
	.GSTR STR?346,"Exactly how does Dark work?"
	.GSTR STR?397,"Examine it."
	.GSTR STR?407,"Examine the gown."
	.GSTR STR?454,"Examine the Thumb while in the Airlock."
	.GSTR STR?550,"Examine all three items."
	.GSTR STR?826,"Synapses? Gray Matter?"
	.GSTR STR?970,"   10  Take the buffered analgesic"
	.GSTR STR?1010,"waiting about 60 turns in Dark to see the hints you get?"
	.GSTR STR?1048,"counting the hors d'oeuvres, the crowd at the Dais, or the guards (at various points)?"
	.GSTR STR?1091,"SMALL PLUG"
	.GSTR STR?1092,"SMALL RECEPTACLE"
	.GSTR STR?49," accomplishes nothing."
	.GSTR STR?145,"The skeleton of a dead Beasthunter lies nearby, clutching something labelled ""Nutrimat/Computer Interface."""
	.GSTR STR?252,"How can I get out of the bedroom?"
	.GSTR STR?293,"How can I buy beer?"
	.GSTR STR?295,"But so what? Ford buys some for you."
	.GSTR STR?296,"How can I buy a packet of peanuts?"
	.GSTR STR?298,"How can I buy a cheese sandwich?"
	.GSTR STR?351,"The second time, hearing will go away. See the third question in this section."
	.GSTR STR?384,"How can I wake Ford?"
	.GSTR STR?402,"How can I get a babel fish?"
	.GSTR STR?406,"Hang something on the hook."
	.GSTR STR?408,"Hang the gown on the hook, then press the button again."
	.GSTR STR?416,"The satchel is bulky. Put it in front of the panel, then push the button again."
	.GSTR STR?467,"How can I enter the sauna?"
	.GSTR STR?553,"How can I open the screening door?"
	.GSTR STR?587,"How can I open the hatch?"
	.GSTR STR?682,"How can I open the toolbox?"
	.GSTR STR?707,"How can I enter the Heart of Gold?"
	.GSTR STR?744,"How can I leave the apartment?"
	.GSTR STR?746,"Dying will get you back to Dark, but that's probably not what you had in mind."
	.GSTR STR?767,"How can I lose my uneasy feeling?"
	.GSTR STR?810,"How can I get the awl?"
	.GSTR STR?848,"The second theory states that the particle was destroyed in the electrical impulse that resulted when you reopened the synapse."
	.GSTR STR?855,"The second goal is to remove your particle of common sense."
	.GSTR STR?862,"How can I get out of the whale?"
	.GSTR STR?917,"The second is in the Airlock of the Vogon ship. It isn't necessary to use the Thumb here, because simply waiting a few turns has the same result."
	.GSTR STR?931,"Hint: You have four different roles over the course of the game: Arthur, Ford, Trillian, and Zaphod."
	.GSTR STR?964,"How can I read the footnotes?"
	.GSTR STR?1088,"RED BUTTON"
	.GSTR STR?1102,"The section tells where each footnote is referenced in the game. Once again, you shouldn't develop this section until you've finished."
	.GSTR STR?26,"There seems to be a noun missing in that sentence."
	.GSTR STR?67,"There are many pieces of mail. Most are from some computer company called Infocom which wants you to buy their games. Hidden underneath is an official letter from the local council, dated some two years ago and inexplicably not delivered till now, explaining that a demolition order has been served on your home. The date of demolition is today's date."
	.GSTR STR?78,"There is a barman serving at the bar."
	.GSTR STR?89,"There is a bottle of mineral water here."
	.GSTR STR?102,"osh"
	.GSTR STR?119,"e h"
	.GSTR STR?130,"fud"
	.GSTR STR?147,"Blocking the gap between two synapses is a large black particle. There seem to be some faint markings on it."
	.GSTR STR?171,"Although you incinerate many, other guards arrive and incinerate you."
	.GSTR STR?210,"Genuine People Personalities"
GPP=STR?210
	.GSTR STR?245,"How do I get out of the dark?"
	.GSTR STR?250,"There is ONE thing you can pick up."
	.GSTR STR?256,"There's an aspirin in the pocket of the gown."
	.GSTR STR?265,"How do I stop the bulldozer?"
	.GSTR STR?266,"There's a tried and true method for stopping bulldozers."
	.GSTR STR?270,"In case you haven't figured it out from these subtle clues, you want to LIE DOWN IN FRONT OF THE BULLDOZER."
	.GSTR STR?303,"There's not much you can do about it."
	.GSTR STR?308,"How do I survive Earth's demolition?"
	.GSTR STR?326,"How do I get out of this Dark?"
	.GSTR STR?331,"There's an important difference between the third and fourth responses."
	.GSTR STR?343,"There is an exit to port. Try going that way."
	.GSTR STR?362,"There are eight exits from Dark (taste never goes away), so there are two Dark exits for each missing sense."
	.GSTR STR?363,"There is a way to differentiate between each pair."
	.GSTR STR?373,"The Earth has been destroyed by the Vogon fleet. You and Ford have hitched a ride aboard one of the ships of the Vogon Fleet by using the electronic Sub-Etha signaling device, also known as a Thumb."
	.GSTR STR?388,"How do I open the case?"
	.GSTR STR?389,"There's a switch and a keyboard attached to the case."
	.GSTR STR?410,"There's only one thing large enough to completely cover the drain."
	.GSTR STR?448,"There's no way to prevent this."
	.GSTR STR?469,"There is no way to actually STAY in the sauna."
	.GSTR STR?470,"Therefore, once Ford, Zaphod, and Trillian enter the sauna, they will be effectively inaccessible to you for the remainder of the game."
	.GSTR STR?482,"But that isn't necessarily the right thing to do."
	.GSTR STR?487,"How does the Nutrimat work?"
	.GSTR STR?500,"ATS is useful, although drinking it is a bad idea."
	.GSTR STR?510,"How do I adjust the circuit board?"
	.GSTR STR?516,"There IS a way to read that message."
	.GSTR STR?600,"There are a total of ten tools scattered throughout the game. For a complete list of them, see the quesion about the tools in the General Questions section."
	.GSTR STR?601,"Even if you've collected all ten tools, you can only carry one at a time into the Access Space..."
	.GSTR STR?604,"There's a way to figure out in advance what tool Marvin will ask you for."
	.GSTR STR?613,"How do I stop the missile attack?"
	.GSTR STR?618,"There's a spare Drive for use during emergencies."
	.GSTR STR?625,"How do I go southwest from the Lair?"
	.GSTR STR?635,"The towel. COVER MY HEAD WITH THE TOWEL or PUT THE TOWEL OVER MY EYES or WRAP THE TOWEL AROUND MY HEAD."
	.GSTR STR?641,"There are at least a dozen ways to say your name: SAY MY NAME or SAY ""ARTHUR DENT"" or SAY ""MY NAME IS ARTHUR DENT"" are some."
	.GSTR STR?650,"There's a way to confuse the Beast into thinking that it has already eaten you."
	.GSTR STR?685,"There aren't a lot of hiding places around the boat."
	.GSTR STR?715,"There is, however, a way to dispose of the rifles."
	.GSTR STR?734,"But that won't happen until you do something else. See the question about the point of the party scene."
	.GSTR STR?747,"There is a way to leave the apartment, but you'll have to solve a puzzle first. See the next question."
	.GSTR STR?749,"There's an item at the party that you have to get back to the Heart of Gold."
	.GSTR STR?755,"There IS a way to stop holding the fluff WITHOUT dropping it."
	.GSTR STR?763,"But this time as Ford Prefect rather than Arthur Dent."
	.GSTR STR?774,"The towel is inside your satchel."
	.GSTR STR?792,"There's not much you can do about the dog at this point."
	.GSTR STR?799,"There's a way to transfer it to something, other than the satchel, so that it will be accessible when you get back to the Heart of Gold."
	.GSTR STR?813,"How do I not get eaten by the dog?"
	.GSTR STR?833,"Can the Maze be mapped?"
	.GSTR STR?836,"The third time you successfully move to a new Maze room (as opposed to being blocked by a synaptic discharge), you'll run across the black particle."
	.GSTR STR?853,"There are two goals for the War Chamber/Maze scene."
	.GSTR STR?863,"There are no exits in any direction."
	.GSTR STR?865,"There's one other way to get out of the whale."
	.GSTR STR?872,"How do I get the pot from the whale?"
	.GSTR STR?873,"There are two ways to do this."
	.GSTR STR?882,"There really isn't much here."
	.GSTR STR?893,"There's something else that you probably haven't noticed about the thing your aunt gave you."
	.GSTR STR?904,"There are 39 Guide entries in the game. A complete list of the topics appears in the MISCELLANEOUS section."
	.GSTR STR?905,"How does the Thumb work?"
	.GSTR STR?915,"There are three points in the game when you can use the Thumb."
	.GSTR STR?918,"The third is Inside the Sperm Whale. Once again, there's an alternative to using the Thumb, but in this case it's not as simple as just waiting. See the INSIDE THE WHALE section for more information."
	.GSTR STR?919,"How do I fix the thumb?"
	.GSTR STR?926,"There does seem to be a lot of it scattered throughout the game."
	.GSTR STR?929,"There are a total of four pieces of fluff in the game. You'll have to find and obtain all four."
	.GSTR STR?975,"   12   Getting the babel fish"
	.GSTR STR?1005,"giving the towel, the thing your aunt gave you, or the satchel to Prosser? (You can only do the last one when you're Ford, of course.)"
	.GSTR STR?1017,"closing the screening door once you've opened it?"
	.GSTR STR?1044,"closing the thing your aunt gave you?"
	.GSTR STR?1065,"BROWNIAN MOTION"
	.GSTR STR?77,"the Pub"
	.GSTR STR?91,"A pair of Vogon guards stand nearby, waving acrid-smelling stun guns an inch away from your face. Simultaneously, they fire."
	.GSTR STR?132,"oll"
	.GSTR STR?199,"He can't hear you above the noise."
ABOVE-NOISE=STR?199
	.GSTR STR?244,"Q = Resume story"
	.GSTR STR?379,"EAT THE PEANUTS."
	.GSTR STR?422,"The upper-half-of-the-room cleaning robot just manages to catch the second item."
	.GSTR STR?541,"Type LOOK three times. The game will then give in and describe the room and the stuff there."
	.GSTR STR?962,"The ultimate goal of the game is to step out onto the surface of Magrathea."
	.GSTR STR?967,"HOW ALL THE POINTS ARE SCORED"
	.GSTR STR?1105," 2  Type FORD, WHAT ABOUT MY HOUSE?"
	.GSTR STR?17,"Sitting in the corner is a spare, portable Improbability Generator."
	.GSTR STR?74,"your Thumb, but before you can hitch a ride the planet is destroyed."
	.GSTR STR?113,"cho"
	.GSTR STR?148,", electrical impulses begin leaping madly across the now unblocked synaptic gap. Unfortunately, YOU were in the gap at the time."
	.GSTR STR?158,"As you begin taking the rifles, so do several of the guards. They may be dim, but they know what to do with a photon rifle."
	.GSTR STR?194," its tungsten carbide Vast-Pain claws"
CLAWS=STR?194
	.GSTR STR?240,"Q = See hint menu"
	.GSTR STR?241," N = Next"
	.GSTR STR?287,"Also, have you noticed the shelf of items behind the bar?"
	.GSTR STR?370,"Where the heck am I?"
	.GSTR STR?371,"As your status line says, you are in the Vogon Hold."
	.GSTR STR?555,"Furthermore, you won't be able to tackle it until you're pretty far into the game. Don't let it worry you until you get up around 200 points."
	.GSTR STR?666,"Where does the Beast go when he sees the black bones?"
	.GSTR STR?680,"Where am I?"
	.GSTR STR?753,"In order to take the fluff, though, you'll have to drop something. This will cause the hostess to start hovering around you. Phil is much too smart to approach you when you're with the hostess."
	.GSTR STR?761,"Where should I go?"
	.GSTR STR?825,"Where is this Maze?"
	.GSTR STR?845,"Where did the black particle go?"
	.GSTR STR?888,"Also, see the question about the screening door in the HEART OF GOLD section."
	.GSTR STR?901,"The various entries in the Guide contain all sorts of useful information and hints that you'll need to solve the puzzles in the game."
	.GSTR STR?911,"Also, the Thumb will break down on its own over the course of the game."
	.GSTR STR?1020,"turning on the spare Drive, plugged into the control panel, before the missile attack begins?"
	.GSTR STR?1021,"turning on the spare Drive during the missile attack, without first plugging it into the control panel?"
	.GSTR STR?1055,"returning to various scenes after you've successfully completed them? Examples: returning to Damogran after stealing the Heart of Gold. Returning to Traal after getting the interface."
	.GSTR STR?1109," 6  Type FOOTNOTE without any number"
	.GSTR STR?24,"The wind moans. Dust drifts across the surface of the alien world. Zaphod, Ford, and Trillian appear and urge you forward."
	.GSTR STR?41,"Playing in this way with"
	.GSTR STR?73,"Ford"
	.GSTR STR?202,"The Hitchhiker's Guide to the Galaxy"
GUIDE-NAME=STR?202
	.GSTR STR?220,"Do you want to get arrested for indecent exposure?"
ARRESTED=STR?220
	.GSTR STR?226,"electronic eye stalk shoots up from the hood, "
EYE-STALK=STR?226
	.GSTR STR?376,"Do you have anything with a lot of protein in it?"
	.GSTR STR?394,"Once you have the babel fish, flip the switch again."
	.GSTR STR?464,"The woman is Tricia MacMillan, known as Trillian. She's an Earthwoman whom you met at a party in Islington not too long ago, at which time you totally failed to impress her. She eventually left the party with a guy named Phil...who is, you realize, the two-headed man standing next to her."
	.GSTR STR?567,"Do you know where you are when you are in the Maze? If not, see the questions on the Maze."
	.GSTR STR?590,"Do you remember an announcement when the Heart of Gold landed on Magrathea?"
	.GSTR STR?597,"Once Marvin has agreed to open the hatch, he tells you to meet him in the Access Space in twelve turns. Make sure you're on hand for that meeting. (Hell hath no depression like a paranoid android scorned.)"
	.GSTR STR?686,"SEARCH THE PILOT SEAT or LOOK UNDER THE CUSHION."
	.GSTR STR?717,"Once you've destroyed the rifles, it's safe to enter the ship."
	.GSTR STR?787,"Once again, think back to what Ford did when you were Arthur."
	.GSTR STR?808,"Do you remember the long piece of text that appeared when your careless words set off an interstellar war?"
	.GSTR STR?824,"Once the dog has been fed, you can survive the War Chamber scene and go on to the Maze."
	.GSTR STR?852,"Do you know the answers to all the other questions in this section?"
	.GSTR STR?903,"Once you know the solutions to all the puzzles, you could play to the end of the game without ever using the Guide."
	.GSTR STR?921,"Once you've summoned the Engineer robot, SHOW (or GIVE) THE THUMB TO THE ENGINEER ROBOT."
	.GSTR STR?963,"Knowing this fact is of virtually no help in getting through the game."
	.GSTR STR?976,"   15   Enjoying the Vogon poetry"
	.GSTR STR?980,"   15   Drinking the beer (as Ford)"
	.GSTR STR?1012,"drinking the Santraginean Mineral Water?"
	.GSTR STR?1032,"drinking the wine at the party?"
	.GSTR STR?1084,"PAN-GALACTIC GARGLE BLASTER"
	.GSTR STR?1093,"SPACE"
	.GSTR STR?31,", and a flathead axe lie by your bed. Before you have a chance to move, Mongol hordes sweep magnificently across the plains of central Asia. They knock down your shack and burn the remains with you inside. You lose interest in the rest of the game."
	.GSTR STR?150,"he rushes toward you, vengeance burning in her eyes."
	.GSTR STR?180," roars off on his ion bike into the Sub-Etha"
ROARS-OFF=STR?180
	.GSTR STR?275,"Standing up to follow him is fatal."
	.GSTR STR?352,"On subsequent visits to Dark, the sense that disappears will be fairly random. See the following question for more details."
	.GSTR STR?353,"Can I control my exit from Darkness?"
	.GSTR STR?359,"Notice anything different about Dark when you use tea instead of ATS?"
	.GSTR STR?413,"Standing or lying in front of the panel won't work."
	.GSTR STR?447,"Can I stop being put in the airlock?"
	.GSTR STR?451,"Can I survive in outer space?"
	.GSTR STR?463,"To find out who owns the ship, stick around on the bridge and pay attention to what everyone is saying."
	.GSTR STR?531,"Can I go aft from Corridor, Aft End?"
	.GSTR STR?627,"Can I stop the Beast from eating me?"
	.GSTR STR?683,"Since it's locked, you'll need to find a key."
	.GSTR STR?687,"Can I stop the boat from crashing?"
	.GSTR STR?699,"Mainly, though, you just need to wait until Trillian shows up."
	.GSTR STR?737,"Notice the fluff?"
	.GSTR STR?764,"The Improbability Drive has sent you back in time and has also changed your identity."
	.GSTR STR?860,"The Improbability Drive, in one of its nastier coincidences, has transported you inside the very same whale you created when you used the Drive to save the ship during the missile attack."
	.GSTR STR?870,"Can I stop the whale from splatting?"
	.GSTR STR?945,"Notice that this rare plant once grew on a tropical world."
	.GSTR STR?1061,"Here's a complete list of things that you can CONSULT the Hitchhiker's Guide about. You should use it only as a last resort, or for your interest once you've finished the game."
	.GSTR STR?1090,"SIRIUS CYBERNETICS CORPORATION"
	.GSTR STR?52,"Nice try."
	.GSTR STR?195," President of the Galaxy"
PRESIDENT=STR?195
	.GSTR STR?536,"Is anything in the Engine Room?"
	.GSTR STR?560,"Can you think of anything contradictory that you could have or do?"
	.GSTR STR?913,"A broken Thumb can be mended."
	.GSTR STR?946,"Can you think of anything around that's similar to a tropical environment?"
	.GSTR STR?948,"Now examine the plant."
	.GSTR STR?993,"looking under your bed?"
	.GSTR STR?1011,"not eating the peanuts in the Vogon Hold?"
	.GSTR STR?110,"cav"
	.GSTR STR?217," A moment later, the dialing tone is suddenly cut off. Glancing through the window you can't help but notice the large old oak tree of which you are particularly fond crashing down through the phone cable."
DIALING-TONE=STR?217
	.GSTR STR?233,"t's a bright morning, the sun is shining, the birds are singing, the meadows are blooming"
NICE-DAY=STR?233
	.GSTR STR?458,"THE VOGON SHIP"
	.GSTR STR?909,"If a ship is within range, you can transport yourself to the ship (via a matter transference beam) by pushing the green button."
	.GSTR STR?1070,"GALACTIC SECURITY AGENCY"
	.GSTR STR?39,"Trying to break"
	.GSTR STR?42,"Fiddling with"
	.GSTR STR?62,"Useless. Utterly useless."
	.GSTR STR?196,"Sirius Cybernetics Corporation"
SCC=STR?196
	.GSTR STR?312,"It has to do with that small black device that Ford drops after the fleet arrives."
	.GSTR STR?418,"Read, very carefully, the paragraph when Ford goes to sleep."
	.GSTR STR?521,"Try examining or reading it."
	.GSTR STR?565,"Does the response to that ring any bells?"
	.GSTR STR?584,"Try examining the mechanism in the Access Space."
	.GSTR STR?714,"Trying to shoot the guards doesn't work either."
	.GSTR STR?754,"So, to get Phil to come over, you'll have to take the item that the hostess keeps offering you. To do so, you'll have to drop something, and the piece of fluff is the only thing you have that you can drop without setting off the hostess again."
	.GSTR STR?766,"Go north to Front of House."
	.GSTR STR?842,"Does that ring a bell?"
	.GSTR STR?988,"  400   TOTAL POINTS"
	.GSTR STR?1023,"not going to the Access Space after asking Marvin to fix the hatch?"
	.GSTR STR?1027,"carving one of the names suggested by the previous item?"
	.GSTR STR?1028,"carving the Beast's name on the memorial?"
	.GSTR STR?8,"In fact, a lethal dose."
	.GSTR STR?9,"Marvin, the Paranoid Android, is here."
	.GSTR STR?34,"autopilot"
	.GSTR STR?176,"If you hyperventilate and then empty your lungs, you will last about thirty seconds in the vacuum of space. However, because space is so vastly hugely mind-bogglingly big, getting picked up by another ship within those thirty seconds is almost infinitely improbable."
SPACE-TEXT=STR?176
	.GSTR STR?236," all circuits are currently engaged by the "
ENGAGED=STR?236
	.GSTR STR?274,"If you take the towel he's trying to give you, he'll walk away."
	.GSTR STR?290,"If you have fewer than three beers, the shock of the matter transference beam will kill you."
	.GSTR STR?291,"If you have more than three beers, you'll get drunk and end up partying through the end of the world."
	.GSTR STR?307,"If you haven't figured it out, you'll find out more later."
	.GSTR STR?329,"If you've waited enough you'll begin to get some clues."
	.GSTR STR?430,"If you want to understand the announcement, you'll have to discover a way to translate it."
	.GSTR STR?453,"If you wait, you'll find yourself in the Dark again."
	.GSTR STR?483,"In fact, when you plug in the spare Drive at the wrong time, Eddie warns you that it's only for emergencies."
	.GSTR STR?494,"In fact, it isn't even in the Heart of Gold."
	.GSTR STR?568,"The Maze is your own brain, and the particle is your common sense. Once you have removed the particle, you will no longer be fettered by common sense and can take NO TEA."
	.GSTR STR?569,"Spelling it out step by step: First, acquire a cup of tea. Then get rid of the common sense particle in the Maze. TAKE TEA THEN TAKE NO TEA. Finally, SHOW THE TEA AND THE NO TEA TO THE SCREENING DOOR."
	.GSTR STR?585,"If you've ever seen the fruit, eating it would provide a big hint."
	.GSTR STR?592,"If you wait the 14.9 years such a check will take, you'll probably die of boredom."
	.GSTR STR?596,"Marvin. See the question about Marvin to figure out how to get him to open the hatch."
	.GSTR STR?598,"Marvin will ask you for the tool he needs to fix the mechanism."
	.GSTR STR?609,"If you meet Marvin there and give him that tool when he asks for it, he will fix the mechanism and open the hatch."
	.GSTR STR?659,"If you could climb them, you might be able to escape the Beast."
	.GSTR STR?660,"If you could collapse them onto the Beast, that just might do it in."
	.GSTR STR?661,"If you could transmute them into steaming mounds of Qurmeesian Mega-Rhino flank steaks, the Beast might start in on those and ignore your few measly pounds of stringy flesh."
	.GSTR STR?706,"If you're still having troubles with the guards, see the next question."
	.GSTR STR?721,"If you've opened the toolbox, then you've certainly found both the seat cushion fluff and the laser-assisted monkey wrench. Getting these two items are the ultimate goal of the Damogran scene."
	.GSTR STR?728,"If you try to talk to Phil, he doesn't notice, and invariably leaves the room."
	.GSTR STR?733,"If you recall from the events on the Bridge of the Heart of Gold, you (Trillian) eventually left ... er, will leave ... the party with Zaphod/Phil."
	.GSTR STR?738,"If you take the fluff from his jacket, it will ""break the ice"" and Arthur will begin jabbering."
	.GSTR STR?742,"If you try to talk to her, you'll learn the meaning of the phrase ""bored to death."""
	.GSTR STR?743,"If you drop your glass of wine, your handbag, or your plate of hors d'oeuvres, the hostess will come over and pester you about it. She won't leave you alone until you take the item that you dropped."
	.GSTR STR?759,"If you're still confused, one sequence of moves that will ""solve"" the party scene is:  EXAMINE ARTHUR. DROP THE WINE. TAKE THE JACKET FLUFF. OPEN THE HANDBAG. PUT THE FLUFF IN THE HANDBAG. TAKE THE WINE. Then just WAIT until Phil comes up and escorts you away. You will end up in Dark."
	.GSTR STR?778,"If you recall from when you were Arthur, it would mean the destruction of Arthur's house if he stood up at this point."
	.GSTR STR?819,"If you examine the dog at the beginning of the game, you'll notice that it's very hungry."
	.GSTR STR?821,"If you want to avoid starting over from the beginning, there's another way to feed the dog."
	.GSTR STR?835,"In fact, the directions in the Maze are totally random, so it makes no difference which direction you move in."
	.GSTR STR?837,"If you ignore the particle, you'll run across it again later."
	.GSTR STR?861,"If you recall, the missiles were turned into a sperm whale, which was last seen plummeting through the atmosphere of Magrathea. This explains why, after a few turns, the whale invariably splats (and you along with it)."
	.GSTR STR?864,"If you wait long enough, you'll splat and return to Dark."
	.GSTR STR?867,"It will also leave you in Dark."
	.GSTR STR?892,"If you leave it behind, it will pop up about a dozen moves later, sometimes on the ground where you are, sometimes in your inventory, and sometimes in your gown pocket. (The thing will only ""follow"" you when you are Arthur.)"
	.GSTR STR?910,"If you press the green button when there is no ship around, you'll break the Thumb."
	.GSTR STR?930,"Try finding them yourself. When you're stumped, return to this question."
	.GSTR STR?955,"Marvin will ask for one of ten different tools."
	.GSTR STR?961,"Solve all the puzzles, reach the end."
	.GSTR STR?1075,"HITCHHIKER'S GUIDE"
	.GSTR STR?1086,"PROTEIN"
	.GSTR STR?1117,"14  When Ford hands you the Guide"
	.GSTR STR?13," about three nanoseconds ago. Sure enough, here comes that huge atomic fireball."
	.GSTR STR?71,"you exclaim"
	.GSTR STR?92,"Along one wall is a tall dispensing machine."
	.GSTR STR?99,"o s"
	.GSTR STR?133,"wro"
	.GSTR STR?208,"A wisp of an inkling of a thought penetrates the three-inch thickness of solid bone surrounding the guards' very tiny brains that something suspicious is going on. "
GUARDS-REALIZE=STR?208
	.GSTR STR?221,"Galactic Security Agency"
AGENCY=STR?221
	.GSTR STR?288,"How much beer should I drink?"
	.GSTR STR?489,"The Nutrimat does all the rest, and in seconds you'll have your very own cup of incredibly delicious Advanced Tea Substitute (ATS)."
	.GSTR STR?564,"Try going back to the beginning of the game and taking or dropping NO TEA."
	.GSTR STR?745,"Try going south from the Living Room."
	.GSTR STR?804,"EARTH, REVISITED"
	.GSTR STR?874,"One way involves the Thumb."
	.GSTR STR?990,"FOR YOUR AMUSEMENT"
	.GSTR STR?1006,"talking to Prosser after the Vogon fleet has arrived?"
	.GSTR STR?1041,"talking to the Vl'Hurg leader or G'Gugvunt leader?"
	.GSTR STR?1042,"dropping something in the Maze (your brain) and then walking around once you've gotten out?"
	.GSTR STR?1043,"talking to the bulldozer driver, the Vogon Captain, or the hostess?"
	.GSTR STR?1067,"EARTH"
	.GSTR STR?1083,"NUTRIMAT"
	.GSTR STR?1095,"TOWEL"
	.GSTR STR?1111," 8  Consult the Guide about fluff"
	.GSTR STR?35,"banner"
	.GSTR STR?59,"Run out on the street and say that. See what happens."
	.GSTR STR?124,"o t"
	.GSTR STR?137,"""Gashee morphousite, thou expungiest quoopisk!"""
	.GSTR STR?276,"Without Ford you'll never survive the upcoming destruction of the Earth."
	.GSTR STR?411,"Cover the drain with the towel, then push the button again."
	.GSTR STR?472,"Without Eddie, who would make all those fun announcements?"
	.GSTR STR?632,"Closing your eyes isn't obvious enough for the Beast to notice."
	.GSTR STR?1038,"shooting the crowd, the guards, Trillian, yourself, the toolbox?"
	.GSTR STR?1039,"ordering GUARDS, SHOOT both before and after they've dropped their photon rifles?"
	.GSTR STR?19,"79,818"
	.GSTR STR?23,"A mist spins round your head. You fall into what seems like a bottomless pit. Suddenly, you hit the bottom so hard that you wish it had been bottomless..."
	.GSTR STR?372,"ASK FORD ABOUT THE EARTH."
	.GSTR STR?868,"Hitchhike using the Thumb."
	.GSTR STR?1018,"reading the tiny message on the circuit board with the magnifying glass?"
	.GSTR STR?1029,"reading the memorial (both before and after carving your name)?"
	.GSTR STR?45,"It dances by you like a thing possessed."
	.GSTR STR?54,"Not bloody likely."
	.GSTR STR?64,"Your gown is here."
	.GSTR STR?186,"It is already open."
ALREADY-OPEN=STR?186
	.GSTR STR?187,"It is already closed."
ALREADY-CLOSED=STR?187
	.GSTR STR?197," matter transference beam"
BEAM=STR?197
	.GSTR STR?211,". Also see the entries on "
ALSO-SEE=STR?211
	.GSTR STR?623,"Turning on the spare Drive while it's plugged into the control console destroys the large plug and large receptacle, so you can only do it once during the game. The one time you want to activate the drive while plugged into the control console is during the missile attack."
	.GSTR STR?657,"It is now safe to remove the towel from your head, and to go southwest from the Lair."
	.GSTR STR?834,"No. The Maze is totally unmappable."
	.GSTR STR?995,"to PHONE HOME from your bedroom?"
	.GSTR STR?1008,"going straight to the Pub when you're Ford, instead of giving Arthur the towel, and then waiting a few turns?"
	.GSTR STR?121,"l m"
	.GSTR STR?286,"Drink some beer."
	.GSTR STR?292,"Drink the beer three times."
	.GSTR STR?338,"Unless you've been to the Vogon Hold, you're at the wrong question."
	.GSTR STR?497,"Open the service panel and remove the circuit board. Now, put the interface inside the Nutrimat. Finally, touch the pad!"
	.GSTR STR?573,"Drink the cup of tea before you enter."
	.GSTR STR?782,"So you have to APPROACH PROSSER or WALK AROUND THE BULLDOZER. Now you can talk to him."
	.GSTR STR?786,"Unless Arthur is with you, you are here prematurely."
	.GSTR STR?1035,"to PICK UP ARTHUR or PICK UP PHIL at the party?"
	.GSTR STR?1110," 7  Shoot the Beast three times"
	.GSTR STR?11," was a bit too much for you. You expire from sheer misery and unhappiness."
	.GSTR STR?27,"[Transcripting o"
	.GSTR STR?79,"However often you do it, you are still stunned by the shock of dematerialisation. The scene around is ripped away like a flimsy backcloth."
	.GSTR STR?163,"  "
	.GSTR STR?213,"It won't budge."
BUDGE=STR?213
	.GSTR STR?242,"P = Previous"
	.GSTR STR?259,"Have you read the mail?"
	.GSTR STR?263,"Have you read the pile of mail on your Front Porch?"
	.GSTR STR?267,"Have you tried phoning the police?"
	.GSTR STR?268,"Have you tried to PROTEST or asked PROSSER, STOP THE BULLDOZER?"
	.GSTR STR?269,"Have you tried to STAND IN FRONT OF THE BULLDOZER?"
	.GSTR STR?306,"Have you examined the dog?"
	.GSTR STR?313,"Have you tried picking it up?"
	.GSTR STR?314,"Have you tried examining it?"
	.GSTR STR?327,"Have patience."
	.GSTR STR?357,"Have you ever examined the cup of tea?"
	.GSTR STR?385,"Have you tried WAKE FORD?"
	.GSTR STR?403,"Have you pressed the dispenser button?"
	.GSTR STR?449,"However, you should make sure that you've accomplished everything that needs to be accomplished aboard the Vogon ship before this occurs."
	.GSTR STR?478,"Have you examined them?"
	.GSTR STR?501,"Have you ever examined it?"
	.GSTR STR?502,"Have you discovered a need for a source of Brownian Motion?"
	.GSTR STR?507,"Have you ever examined the tea?"
	.GSTR STR?512,"Have you examined it?"
	.GSTR STR?515,"Have you noticed the message in tiny letters on the board?"
	.GSTR STR?522,"Have you opened the carton?"
	.GSTR STR?523,"The Sirius Cybernetics Corporation has apparently screwed up (a common occurrence) and put the wrong item inside the shipping carton."
	.GSTR STR?526,"Have you examined or read it?"
	.GSTR STR?528,"Have you tried shooting the gun at the Beast?"
	.GSTR STR?529,"Have you tried it several times?"
	.GSTR STR?537,"Have you gotten into the Engine Room? If not, you should do so before looking at the next hint."
	.GSTR STR?539,"However, after losing that argument with you, the game is probably a bit peeved and is acting petulant."
	.GSTR STR?547,"Have you seen any hot liquids?"
	.GSTR STR?562,"Have you noticed what happens when you take or drop the (real) tea?"
	.GSTR STR?566,"Have you ever read or examined the black particle in the Maze?"
	.GSTR STR?572,"Have you ever done anything that made you very happy and contented?"
	.GSTR STR?578,"Have you ever followed Marvin when he appears around the Heart of Gold?"
	.GSTR STR?588,"Have you tried OPEN THE HATCH?"
	.GSTR STR?630,"Have you read the Guide entry on the Ravenous Bugblatter Beast of Traal?"
	.GSTR STR?639,"Have you been in the Beast's Outer Lair?"
	.GSTR STR?640,"Have you ever tried saying your name as the Beast demands?"
	.GSTR STR?646,"Have you figured out why the Beast wants to know your name?"
	.GSTR STR?648,"Have you figured out how to stop the Beast from attacking you, at least on a temporary basis?"
	.GSTR STR?665,"Have you tried painting the bones with the paint?"
	.GSTR STR?673,"Have you been in the Inner Lair?"
	.GSTR STR?695,"Leave the boat. Type NORTH or LEAVE THE BOAT."
	.GSTR STR?720,"Have you opened the toolbox?"
	.GSTR STR?729,"Have you examined him?"
	.GSTR STR?768,"Have you tried waiting a few turns?"
	.GSTR STR?806,"Have you tried listening to the conversation?"
	.GSTR STR?807,"Have you examined the approaching star system?"
	.GSTR STR?816,"Have you seen a dog anywhere else?"
	.GSTR STR?839,"Have you read the markings on the particle?"
	.GSTR STR?890,"Have you tried getting rid of it?"
	.GSTR STR?927,"Have you consulted the Guide about fluff?"
	.GSTR STR?939,"A tiny plant will sprout around ten moves later."
	.GSTR STR?959,"Have you tried asking some of the other characters in the story?"
	.GSTR STR?960,"Have fun, be happy."
	.GSTR STR?992,"Have you tried..."
	.GSTR STR?1031,"waking the sleeping Beast?"
	.GSTR STR?1068,"FLUFF"
	.GSTR STR?1096,"VOGON POETRY"
	.GSTR STR?1097,"VOGONS"
	.GSTR STR?1106," 3  Upon arrival at the Speedboat"
	.GSTR STR?21,"You are disoriented. Blackness swims toward you like a shoal of eels who have just seen something that eels like a lot..."
	.GSTR STR?56,"You are clearly insane."
	.GSTR STR?57,"You appear to have gone barking mad."
	.GSTR STR?111,"s g"
	.GSTR STR?160,"You are in the stomach of a sperm whale. You can hear a distant sound of rushing wind."
	.GSTR STR?165,"      "
	.GSTR STR?166,"        "
	.GSTR STR?167,"          "
	.GSTR STR?185,"You already are!"
YOU-ARE=STR?185
	.GSTR STR?216," with passion, and ignores a passing microscopic space fleet."
WITH-PASSION=STR?216
	.GSTR STR?223,"Despite your hangover, you recall that Zaphod and water don't mix."
DONT-MIX=STR?223
	.GSTR STR?230,"A small upper-half-of-the-room cleaning robot flies into the room, "
ROBOT-FLIES-IN=STR?230
	.GSTR STR?246,"TURN ON THE LIGHT."
	.GSTR STR?278,"Or you can say FORD, WHAT ABOUT MY HOME? as soon as he arrives."
	.GSTR STR?280,"Don't stand up until Prosser is lying down in your place."
	.GSTR STR?325,"...but in this case, you'll have to do more than just wait."
	.GSTR STR?332,"You are no longer told that you can't smell anything."
	.GSTR STR?355,"Don't continue until you have a cup of tea."
	.GSTR STR?356,"Don't continue until you have real tea, not merely Advanced Tea Substitute."
	.GSTR STR?437,"Don't go on unless you've translated the garbled announcement."
	.GSTR STR?438,"Don't go on until you've figured out what's going on with the glass case and switch and keyboard."
	.GSTR STR?439,"You are at a Vogon Poetry Appreciation Session. The Vogon Captain is about to read you his favourite poem. The Guide's entry on Vogon Poetry makes clear that this is extremely nasty."
	.GSTR STR?452,"Yes. In fact, there's no way to NOT survive it."
	.GSTR STR?480,"Don't go on until you've figured out how to set up and use the spare Improbability Drive."
	.GSTR STR?495,"Don't go on unless you have the Nutrimat/Computer Interface (not to be confused with the shipping carton for the interface)."
	.GSTR STR?505,"Don't go on unless you actually have the cup of tea."
	.GSTR STR?506,"Don't go on unless this cup of tea is REAL tea, not just Advanced Tea Substitute (ATS)."
	.GSTR STR?517,"Don't go on until you've been on Damogran."
	.GSTR STR?518,"Don't go on until you've opened the toolbox."
	.GSTR STR?527,"Don't go on unless you've been in the Lair."
	.GSTR STR?556,"Don't develop any further unless you've gotten the cup of tea (real tea, not Advanced Tea Substitute)."
	.GSTR STR?581,"Don't go on until you've been in Marvin's Pantry."
	.GSTR STR?606,"Don't go on until you've seen the fruit."
	.GSTR STR?612,"Start waiting for the next exciting Hitchhiker's game."
	.GSTR STR?649,"Don't go on until you have figured out how to convince the Beast that it can't see you."
	.GSTR STR?664,"Don't go on until you've found the black paint."
	.GSTR STR?672,"Don't go on until the Beast is sleeping."
	.GSTR STR?701,"Don't go on unless you're on the Dais and Trillian is there."
	.GSTR STR?710,"Don't go on unless you've disarmed the guards (see the previous question)."
	.GSTR STR?719,"Don't go on until you ended the scene by successfully entering the Heart of Gold. (If you were killed by the guards, you were NOT successful.)"
	.GSTR STR?762,"You are reliving the last few minutes before the destruction of the Earth."
	.GSTR STR?776,"Don't go on until you've done the step called for by the previous question."
	.GSTR STR?832,"You are, improbably enough, inside your own brain!"
	.GSTR STR?869,"The Thumb is probably broken, though. You'll have to get it fixed by an Engineer robot."
	.GSTR STR?906,"The Thumb is an electronic Sub-Etha Auto-Hitching Device. If used properly, it will allow you to hitch rides aboard passing spaceships."
	.GSTR STR?936,"Don't continue until you have the flowerpot."
	.GSTR STR?1118,"15  Read the banner at the Dais"
	.GSTR STR?5,"PRSI"
	.GSTR STR?25,"OOPS"
	.GSTR STR?44,"It slips through your fumbling fingers and hits the carpet with a nerve-shattering bang."
	.GSTR STR?122,"ork"
	.GSTR STR?193,"It looks like"
IT-LOOKS-LIKE=STR?193
	.GSTR STR?253,"You bounce off the doorframe because the room is spinning from your hangover."
	.GSTR STR?321,"Help! I'm stuck in the Dark!"
	.GSTR STR?337,"Help! I'm in the blasted Dark AGAIN!"
	.GSTR STR?652,"Of course, you'll need something to carve with."
	.GSTR STR?994,"enjoying the mud while you're lying in front of the bulldozer?"
	.GSTR STR?1002,"hitting Prosser (before and after your house is demolished)?"
	.GSTR STR?1003,"enjoying your house after it's been demolished?"
	.GSTR STR?1009,"yelling in the Dark?"
	.GSTR STR?1014,"enjoying the Vogon poetry without the babel fish?"
	.GSTR STR?1057,"answering the game's various rhetorical questions, such as ""Did you have a particular direction in mind?"" or ""Don't you think it would be a bad idea to leave the ceremonies?"", by typing YES or NO?"
	.GSTR STR?1114,"11  This footnote is not referenced"
	.GSTR STR?53,"You can't be serious."
	.GSTR STR?98,"kwa"
	.GSTR STR?126,"x j"
	.GSTR STR?159," reduce you to a smoking pile of ash."
	.GSTR STR?181,"He fiddles with the Thumb for a moment or two before handing it back. "
FIDDLES=STR?181
	.GSTR STR?184,"You can't go that way."
CANT-GO=STR?184
	.GSTR STR?189,"You can't do that while you're lying down!"
WHILE-LYING=STR?189
	.GSTR STR?284,"You came here because of Ford, right?"
	.GSTR STR?294,"You can't."
	.GSTR STR?386,"You can't wake Ford."
	.GSTR STR?420,"You can put an object on top of the satchel."
	.GSTR STR?485,"You can only use the drive while connected to the controls ONCE during the course of the game."
	.GSTR STR?488,"All you have to do is touch the touch-sensitive pad."
	.GSTR STR?511,"You can remove it from the Nutrimat."
	.GSTR STR?513,"You can flip any of the eight dipswitches."
	.GSTR STR?514,"You can even flip them while the circuit board is still in the Nutrimat."
	.GSTR STR?574,"Is Marvin important?"
	.GSTR STR?577,"After that point, he'll grudgingly consent to ONE task."
	.GSTR STR?626,"Figuring out how to subdue the Beast would help."
	.GSTR STR?693,"After three turns of heading toward an obstacle, the autopilot will kick on and navigate you safely to your destination."
	.GSTR STR?709,"After Trillian shows up, attempting to enter the Heart of Gold is deadly."
	.GSTR STR?757,"You can put the fluff in your handbag."
	.GSTR STR?790,"You can BUY SOME PEANUTS, but it isn't necessary to do so."
	.GSTR STR?803,"After Arthur runs back to his house (now rubble), follow him and give him the fluff. He'll accept it at this point and put it in his pocket. Then just wait for events to run their course, and you'll soon find yourself back in Dark. When you get back to the Heart of Gold, the satchel fluff should be in the pocket of your gown."
	.GSTR STR?894,"You can put things in it. In fact, you can put almost every takeable item into the thing at the same time."
	.GSTR STR?908,"You can examine the Thumb to determine whether a spaceship is within range. (If the lights are flashing, a ship is nearby.)"
	.GSTR STR?920,"You can't. Only the Engineer robot can fix the Thumb."
	.GSTR STR?932,"You can obtain one piece of fluff during each role."
	.GSTR STR?942,"Left to itself, the tiny sprout will never grow any further."
	.GSTR STR?984,"  100   Drinking the tea"
	.GSTR STR?1046,"typing I AM ARTHUR DENT to the game (as opposed to while talking to a character in the game)?"
	.GSTR STR?1049,"typing PANIC?  How about DON'T PANIC?"
	.GSTR STR?1050,"typing DON'T LOOK or DON'T WAIT or DON'T (anything else)?"
	.GSTR STR?1051,"typing GIVE UP or THROW IN THE TOWEL or PULL MYSELF TOGETHER?"
	.GSTR STR?1053,"typing ESCAPE at any point?"
	.GSTR STR?1056,"typing APPLAUD at any point (other than during the poetry reading)?"
	.GSTR STR?1058,"typing APPRECIATE [something]?"
	.GSTR STR?1077,"INFOCOM"
	.GSTR STR?1107," 4  Listen to the music in the Pub"
	.GSTR STR?153,"but a split second later the boat smashes into the rocks."
	.GSTR STR?155,". The excitement overwhelms you (or perhaps it's just the awesome hangover from last night)."
	.GSTR STR?318,"You didn't drink enough beer."
	.GSTR STR?594,"You don't have the necessary intelligence for the task."
	.GSTR STR?629,"Leaving the room (EAST) will buy you some time."
	.GSTR STR?655,"Use one of the sharp stones that are lying on the ground."
	.GSTR STR?999,"listening to the jukebox music (several times, then again when you're Ford)?"
	.GSTR STR?1098,"WALKING"
	.GSTR STR?82,"newts he has known."
	.GSTR STR?127,"erl"
	.GSTR STR?203," But then again you must already know that, since you bought one."
ALREADY-KNOW-THAT=STR?203
	.GSTR STR?277,"Ford is oblivious to your problem. If you wait, he'll notice the bulldozer, and help you out."
	.GSTR STR?289,"Ford will keep urging you to drink beer until you've had enough."
	.GSTR STR?309,"DON'T PANIC."
	.GSTR STR?311,"Remember Ford's reason for drinking all that beer?"
	.GSTR STR?322,"If this ""Dark"" is at the very beginning of the game, you're in the wrong place. Look at the very first question."
	.GSTR STR?347,"You enter Dark when Earth is destroyed, and other times throughout the game."
	.GSTR STR?390,"SAVE first, then try typing on the keyboard. For example, TYPE ""HELLO."""
	.GSTR STR?392,"If the recording was gibberish, you'll have to find a way to translate it."
	.GSTR STR?423,"If there were several items on the satchel, they would all fly into the air and confuse the flying robot."
	.GSTR STR?621,"If there are fused spots where the large plug and large receptacle used to be, you plugged the drive in at the wrong time."
	.GSTR STR?724,"Remember what happened when you first reached the Bridge of the Heart of Gold?"
	.GSTR STR?827,"Remember you were just teleported over from a microscopic space fleet..."
	.GSTR STR?831,"Remember, the Vl'Hurgs and G'Gugvunts were teleporting you back to the Heart of Gold."
	.GSTR STR?912,"If the Thumb is broken, you will not be transported when you press the green button, even if a ship is nearby."
	.GSTR STR?922,"If the robot claims that there's nothing wrong with the Thumb, then it wasn't broken."
	.GSTR STR?923,"If the Thumb is broken, the Engineer robot won't agree to fix it unless you also SHOW THE GUARANTEE TO THE ENGINEER ROBOT."
	.GSTR STR?949,"Now see the question about opening the hatch in the Heart of Gold section."
	.GSTR STR?951,"Many of them are rather excitingly high-tech, aren't they?"
	.GSTR STR?1007,"eating the cheese sandwich when you're Ford?"
	.GSTR STR?1033,"eating one of the hors d'oeuvres? (Try several times.)"
	.GSTR STR?1052,"brushing your teeth with the toothbrush?"
	.GSTR STR?1112," 9  ASK GUIDE ABOUT SPACE in space"
	.GSTR STR?48," doesn't do anything."
	.GSTR STR?83,"cricket."
	.GSTR STR?235,"You fumble with the Thumb as you hold onto the tree against the fierce wind. It falls to the ground near Arthur's feet."
THUMB-FUMBLE=STR?235
	.GSTR STR?344,"Be persistent. Try going PORT a few more times."
	.GSTR STR?445,"Now that you've heard the glass case's recording AND the second verse of the poem, you know what to type on the keyboard to get the atomic vector plotter. (When the guards drag you back into the Vogon Hold, of course.)"
	.GSTR STR?549,"Now that you have all three items (spare Drive, plotter, and cup of ATS), you should be able to figure out how to hook them together."
	.GSTR STR?935,"Now that you have all four pieces of fluff, any idea what to do with them?"
	.GSTR STR?1054,"filling anything?"
	.GSTR STR?1073,"GREEN BUTTON"
	.GSTR STR?36,"."
	.GSTR STR?76,"Behind the bar is a shelf. It is full of the sort of items you find on shelves behind bars in pubs."
	.GSTR STR?85,"the deteriorating condition of the motorways."
	.GSTR STR?93,"In the corner is a glass case with a switch and a keyboard."
	.GSTR STR?95,"toy"
	.GSTR STR?228," Infinite Improbability Drive"
IID=STR?228
	.GSTR STR?302,"My home's being wrecked. What now?"
	.GSTR STR?369,"IN THE DARK"
	.GSTR STR?602,"...and you don't have time to go out and get a different one before Marvin gives up and leaves..."
	.GSTR STR?603,"...and Marvin will NEVER ask for the tool you happen to be holding."
	.GSTR STR?679,"Ask the game! (Type WHO AM I?)"
	.GSTR STR?723,"Ask the game. (Type WHO AM I?)"
	.GSTR STR?876,"To obtain the flowerpot using the thumb, just pick up the pot and hitchhike."
	.GSTR STR?878,"To obtain the flowerpot using the aunt's gift: the aunt's gift has an unusual property you may not have discovered. See the question about the aunt's gift."
	.GSTR STR?998,"buying peanuts (as Arthur)?"
	.GSTR STR?1001,"feeding peanuts to the dog? (You can only do this as Ford, of course.)"
	.GSTR STR?1104," 1  ENJOY THE DARKNESS in the Dark"

	.ENDI
